package dcamapi;

import dcamapi.DcamapiLibrary.DCAMPROPATTRIBUTE;
import dcamapi.DcamapiLibrary.DCAMPROPATTRIBUTE2;
import dcamapi.DcamapiLibrary.DCAMPROPUNIT;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamprop.h</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_PROPERTYATTR extends StructObject
{
  public DCAM_PROPERTYATTR()
  {
    super();
  }

  /**
   * input parameters<br>
   * size of this structure
   */
  @CLong
  @Field(0)
  public long cbSize()
  {
    return this.io.getCLongField(this, 0);
  }

  /**
   * input parameters<br>
   * size of this structure
   */
  @CLong
  @Field(0)
  public DCAM_PROPERTYATTR cbSize(final long cbSize)
  {
    this.io.setCLongField(this, 0, cbSize);
    return this;
  }

  // / DCAMIDPROPERTY
  @CLong
  @Field(1)
  public long iProp()
  {
    return this.io.getCLongField(this, 1);
  }

  // / DCAMIDPROPERTY
  @CLong
  @Field(1)
  public DCAM_PROPERTYATTR iProp(final long iProp)
  {
    this.io.setCLongField(this, 1, iProp);
    return this;
  }

  // / DCAMPROPOPTION
  @CLong
  @Field(2)
  public long option()
  {
    return this.io.getCLongField(this, 2);
  }

  // / DCAMPROPOPTION
  @CLong
  @Field(2)
  public DCAM_PROPERTYATTR option(final long option)
  {
    this.io.setCLongField(this, 2, option);
    return this;
  }

  // / must be 0
  @CLong
  @Field(3)
  public long iReserved1()
  {
    return this.io.getCLongField(this, 3);
  }

  // / must be 0
  @CLong
  @Field(3)
  public DCAM_PROPERTYATTR iReserved1(final long iReserved1)
  {
    this.io.setCLongField(this, 3, iReserved1);
    return this;
  }

  /**
   * output parameters<br>
   * DCAMPROPATTRIBUTE<br>
   * C type : DCAMPROPATTRIBUTE
   */
  @Field(4)
  public IntValuedEnum<DCAMPROPATTRIBUTE> attribute()
  {
    return this.io.getEnumField(this, 4);
  }

  /**
   * output parameters<br>
   * DCAMPROPATTRIBUTE<br>
   * C type : DCAMPROPATTRIBUTE
   */
  @Field(4)
  public DCAM_PROPERTYATTR attribute(final IntValuedEnum<DCAMPROPATTRIBUTE> attribute)
  {
    this.io.setEnumField(this, 4, attribute);
    return this;
  }

  // / 0 reserved; DCAMIDGROUP
  @CLong
  @Field(5)
  public long iGroup()
  {
    return this.io.getCLongField(this, 5);
  }

  // / 0 reserved; DCAMIDGROUP
  @CLong
  @Field(5)
  public DCAM_PROPERTYATTR iGroup(final long iGroup)
  {
    this.io.setCLongField(this, 5, iGroup);
    return this;
  }

  /**
   * DCAMPROPUNIT<br>
   * C type : DCAMPROPUNIT
   */
  @Field(6)
  public IntValuedEnum<DCAMPROPUNIT> iUnit()
  {
    return this.io.getEnumField(this, 6);
  }

  /**
   * DCAMPROPUNIT<br>
   * C type : DCAMPROPUNIT
   */
  @Field(6)
  public DCAM_PROPERTYATTR iUnit(final IntValuedEnum<DCAMPROPUNIT> iUnit)
  {
    this.io.setEnumField(this, 6, iUnit);
    return this;
  }

  /**
   * DCAMPROPATTRIBUTE2<br>
   * C type : DCAMPROPATTRIBUTE2
   */
  @Field(7)
  public IntValuedEnum<DCAMPROPATTRIBUTE2> attribute2()
  {
    return this.io.getEnumField(this, 7);
  }

  /**
   * DCAMPROPATTRIBUTE2<br>
   * C type : DCAMPROPATTRIBUTE2
   */
  @Field(7)
  public DCAM_PROPERTYATTR attribute2(final IntValuedEnum<DCAMPROPATTRIBUTE2> attribute2)
  {
    this.io.setEnumField(this, 7, attribute2);
    return this;
  }

  // / minimum value
  @Field(8)
  public double valuemin()
  {
    return this.io.getDoubleField(this, 8);
  }

  // / minimum value
  @Field(8)
  public DCAM_PROPERTYATTR valuemin(final double valuemin)
  {
    this.io.setDoubleField(this, 8, valuemin);
    return this;
  }

  // / maximum value
  @Field(9)
  public double valuemax()
  {
    return this.io.getDoubleField(this, 9);
  }

  // / maximum value
  @Field(9)
  public DCAM_PROPERTYATTR valuemax(final double valuemax)
  {
    this.io.setDoubleField(this, 9, valuemax);
    return this;
  }

  // / minimum stepping between a value and the next
  @Field(10)
  public double valuestep()
  {
    return this.io.getDoubleField(this, 10);
  }

  // / minimum stepping between a value and the next
  @Field(10)
  public DCAM_PROPERTYATTR valuestep(final double valuestep)
  {
    this.io.setDoubleField(this, 10, valuestep);
    return this;
  }

  // / default value
  @Field(11)
  public double valuedefault()
  {
    return this.io.getDoubleField(this, 11);
  }

  // / default value
  @Field(11)
  public DCAM_PROPERTYATTR valuedefault(final double valuedefault)
  {
    this.io.setDoubleField(this, 11, valuedefault);
    return this;
  }

  /**
   * available from DCAM-API 3.0<br>
   * max channel if supports
   */
  @CLong
  @Field(12)
  public long nMaxChannel()
  {
    return this.io.getCLongField(this, 12);
  }

  /**
   * available from DCAM-API 3.0<br>
   * max channel if supports
   */
  @CLong
  @Field(12)
  public DCAM_PROPERTYATTR nMaxChannel(final long nMaxChannel)
  {
    this.io.setCLongField(this, 12, nMaxChannel);
    return this;
  }

  // / reserved to 0
  @CLong
  @Field(13)
  public long iReserved3()
  {
    return this.io.getCLongField(this, 13);
  }

  // / reserved to 0
  @CLong
  @Field(13)
  public DCAM_PROPERTYATTR iReserved3(final long iReserved3)
  {
    this.io.setCLongField(this, 13, iReserved3);
    return this;
  }

  // / max view if supports
  @CLong
  @Field(14)
  public long nMaxView()
  {
    return this.io.getCLongField(this, 14);
  }

  // / max view if supports
  @CLong
  @Field(14)
  public DCAM_PROPERTYATTR nMaxView(final long nMaxView)
  {
    this.io.setCLongField(this, 14, nMaxView);
    return this;
  }

  /**
   * available from DCAM-API 3.03<br>
   * number of elements for array
   */
  @CLong
  @Field(15)
  public long iPropNumberOfElement()
  {
    return this.io.getCLongField(this, 15);
  }

  /**
   * available from DCAM-API 3.03<br>
   * number of elements for array
   */
  @CLong
  @Field(15)
  public DCAM_PROPERTYATTR iPropNumberOfElement(final long iPropNumberOfElement)
  {
    this.io.setCLongField(this, 15, iPropNumberOfElement);
    return this;
  }

  // / base id of array if element
  @CLong
  @Field(16)
  public long iPropArrayBase()
  {
    return this.io.getCLongField(this, 16);
  }

  // / base id of array if element
  @CLong
  @Field(16)
  public DCAM_PROPERTYATTR iPropArrayBase(final long iPropArrayBase)
  {
    this.io.setCLongField(this, 16, iPropArrayBase);
    return this;
  }

  // / step for iProp to next element
  @CLong
  @Field(17)
  public long iPropStepElement()
  {
    return this.io.getCLongField(this, 17);
  }

  // / step for iProp to next element
  @CLong
  @Field(17)
  public DCAM_PROPERTYATTR iPropStepElement(final long iPropStepElement)
  {
    this.io.setCLongField(this, 17, iPropStepElement);
    return this;
  }

  public DCAM_PROPERTYATTR(final Pointer pointer)
  {
    super(pointer);
  }
}
