package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:509</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_USERDATATEXT extends StructObject
{
  public DCAM_USERDATATEXT()
  {
    super();
  }

  // / C type : DCAM_METADATAHDR
  @Field(0)
  public DCAM_METADATAHDR hdr()
  {
    return this.io.getNativeObjectField(this, 0);
  }

  // / C type : DCAM_METADATAHDR
  @Field(0)
  public DCAM_USERDATATEXT hdr(final DCAM_METADATAHDR hdr)
  {
    this.io.setNativeObjectField(this, 0, hdr);
    return this;
  }

  // / C type : char*
  @Field(1)
  public Pointer<Byte> text()
  {
    return this.io.getPointerField(this, 1);
  }

  // / C type : char*
  @Field(1)
  public DCAM_USERDATATEXT text(final Pointer<Byte> text)
  {
    this.io.setPointerField(this, 1, text);
    return this;
  }

  @CLong
  @Field(2)
  public long textLen()
  {
    return this.io.getCLongField(this, 2);
  }

  @CLong
  @Field(2)
  public DCAM_USERDATATEXT textLen(final long textLen)
  {
    this.io.setCLongField(this, 2, textLen);
    return this;
  }

  // / character encoding scheme, DCAM_CES_UTF8...
  @CLong
  @Field(3)
  public long textKind()
  {
    return this.io.getCLongField(this, 3);
  }

  // / character encoding scheme, DCAM_CES_UTF8...
  @CLong
  @Field(3)
  public DCAM_USERDATATEXT textKind(final long textKind)
  {
    this.io.setCLongField(this, 3, textKind);
    return this;
  }

  public DCAM_USERDATATEXT(final Pointer pointer)
  {
    super(pointer);
  }
}
