package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib/dcam/inc/dcamapi3.h</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class dcam_rgbratio extends StructObject
{
  public dcam_rgbratio()
  {
    super();
  }

  @Field(0)
  public double red()
  {
    return this.io.getDoubleField(this, 0);
  }

  @Field(0)
  public dcam_rgbratio red(final double red)
  {
    this.io.setDoubleField(this, 0, red);
    return this;
  }

  @Field(1)
  public double green()
  {
    return this.io.getDoubleField(this, 1);
  }

  @Field(1)
  public dcam_rgbratio green(final double green)
  {
    this.io.setDoubleField(this, 1, green);
    return this;
  }

  @Field(2)
  public double blue()
  {
    return this.io.getDoubleField(this, 2);
  }

  @Field(2)
  public dcam_rgbratio blue(final double blue)
  {
    this.io.setDoubleField(this, 2, blue);
    return this;
  }

  public dcam_rgbratio(final Pointer pointer)
  {
    super(pointer);
  }
}
