package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:344</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAMDEV_OPEN extends StructObject
{
  public DCAMDEV_OPEN()
  {
    super();
  }

  // / [in]
  @CLong
  @Field(0)
  public long size()
  {
    return this.io.getCLongField(this, 0);
  }

  // / [in]
  @CLong
  @Field(0)
  public DCAMDEV_OPEN size(final long size)
  {
    this.io.setCLongField(this, 0, size);
    return this;
  }

  // / [in]
  @CLong
  @Field(1)
  public long index()
  {
    return this.io.getCLongField(this, 1);
  }

  // / [in]
  @CLong
  @Field(1)
  public DCAMDEV_OPEN index(final long index)
  {
    this.io.setCLongField(this, 1, index);
    return this;
  }

  /**
   * [out]<br>
   * C type : HDCAM
   */
  @Field(2)
  public Pointer<HDCAM_struct> hdcam()
  {
    return this.io.getPointerField(this, 2);
  }

  /**
   * [out]<br>
   * C type : HDCAM
   */
  @Field(2)
  public DCAMDEV_OPEN hdcam(final Pointer<HDCAM_struct> hdcam)
  {
    this.io.setPointerField(this, 2, hdcam);
    return this;
  }

  public DCAMDEV_OPEN(final Pointer pointer)
  {
    super(pointer);
  }
}
