package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib/dcam/inc/dcamapi3.h</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_SIZE extends StructObject
{
  public DCAM_SIZE()
  {
    super();
  }

  @CLong
  @Field(0)
  public long cx()
  {
    return this.io.getCLongField(this, 0);
  }

  @CLong
  @Field(0)
  public DCAM_SIZE cx(final long cx)
  {
    this.io.setCLongField(this, 0, cx);
    return this;
  }

  @CLong
  @Field(1)
  public long cy()
  {
    return this.io.getCLongField(this, 1);
  }

  @CLong
  @Field(1)
  public DCAM_SIZE cy(final long cy)
  {
    this.io.setCLongField(this, 1, cy);
    return this;
  }

  public DCAM_SIZE(final Pointer pointer)
  {
    super(pointer);
  }
}
