package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:563</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAMREC_STATUS extends StructObject
{
  public DCAMREC_STATUS()
  {
    super();
  }

  @CLong
  @Field(0)
  public long size()
  {
    return this.io.getCLongField(this, 0);
  }

  @CLong
  @Field(0)
  public DCAMREC_STATUS size(final long size)
  {
    this.io.setCLongField(this, 0, size);
    return this;
  }

  @CLong
  @Field(1)
  public long currentsessionIndex()
  {
    return this.io.getCLongField(this, 1);
  }

  @CLong
  @Field(1)
  public DCAMREC_STATUS currentsessionIndex(final long currentsessionIndex)
  {
    this.io.setCLongField(this, 1, currentsessionIndex);
    return this;
  }

  @CLong
  @Field(2)
  public long maxframecountPerSession()
  {
    return this.io.getCLongField(this, 2);
  }

  @CLong
  @Field(2)
  public DCAMREC_STATUS maxframecountPerSession(final long maxframecountPerSession)
  {
    this.io.setCLongField(this, 2, maxframecountPerSession);
    return this;
  }

  @CLong
  @Field(3)
  public long currentframeIndex()
  {
    return this.io.getCLongField(this, 3);
  }

  @CLong
  @Field(3)
  public DCAMREC_STATUS currentframeIndex(final long currentframeIndex)
  {
    this.io.setCLongField(this, 3, currentframeIndex);
    return this;
  }

  @CLong
  @Field(4)
  public long missingframeCount()
  {
    return this.io.getCLongField(this, 4);
  }

  @CLong
  @Field(4)
  public DCAMREC_STATUS missingframeCount(final long missingframeCount)
  {
    this.io.setCLongField(this, 4, missingframeCount);
    return this;
  }

  @CLong
  @Field(5)
  public long flags()
  {
    return this.io.getCLongField(this, 5);
  }

  @CLong
  @Field(5)
  public DCAMREC_STATUS flags(final long flags)
  {
    this.io.setCLongField(this, 5, flags);
    return this;
  }

  @CLong
  @Field(6)
  public long totalframecount()
  {
    return this.io.getCLongField(this, 6);
  }

  @CLong
  @Field(6)
  public DCAMREC_STATUS totalframecount(final long totalframecount)
  {
    this.io.setCLongField(this, 6, totalframecount);
    return this;
  }

  @CLong
  @Field(7)
  public long reserved()
  {
    return this.io.getCLongField(this, 7);
  }

  @CLong
  @Field(7)
  public DCAMREC_STATUS reserved(final long reserved)
  {
    this.io.setCLongField(this, 7, reserved);
    return this;
  }

  public DCAMREC_STATUS(final Pointer pointer)
  {
    super(pointer);
  }
}
