package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:529</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_TIMESTAMPBLOCK extends StructObject
{
  public DCAM_TIMESTAMPBLOCK()
  {
    super();
  }

  // / C type : DCAM_METADATABLOCKHDR
  @Field(0)
  public DCAM_METADATABLOCKHDR hdr()
  {
    return this.io.getNativeObjectField(this, 0);
  }

  // / C type : DCAM_METADATABLOCKHDR
  @Field(0)
  public DCAM_TIMESTAMPBLOCK hdr(final DCAM_METADATABLOCKHDR hdr)
  {
    this.io.setNativeObjectField(this, 0, hdr);
    return this;
  }

  /**
   * [in] pointer for TIMESTAMP block<br>
   * C type : DCAM_TIMESTAMP*
   */
  @Field(1)
  public Pointer<DCAM_TIMESTAMP> timestamps()
  {
    return this.io.getPointerField(this, 1);
  }

  /**
   * [in] pointer for TIMESTAMP block<br>
   * C type : DCAM_TIMESTAMP*
   */
  @Field(1)
  public DCAM_TIMESTAMPBLOCK timestamps(final Pointer<DCAM_TIMESTAMP> timestamps)
  {
    this.io.setPointerField(this, 1, timestamps);
    return this;
  }

  // / [in] sizeof(DCAM_TIMESTRAMP)
  @CLong
  @Field(2)
  public long timestampsize()
  {
    return this.io.getCLongField(this, 2);
  }

  // / [in] sizeof(DCAM_TIMESTRAMP)
  @CLong
  @Field(2)
  public DCAM_TIMESTAMPBLOCK timestampsize(final long timestampsize)
  {
    this.io.setCLongField(this, 2, timestampsize);
    return this;
  }

  // / [o] return the written data size of DCAM_TIMESTRAMP.
  @CLong
  @Field(3)
  public long timestampvaildsize()
  {
    return this.io.getCLongField(this, 3);
  }

  // / [o] return the written data size of DCAM_TIMESTRAMP.
  @CLong
  @Field(3)
  public DCAM_TIMESTAMPBLOCK timestampvaildsize(final long timestampvaildsize)
  {
    this.io.setCLongField(this, 3, timestampvaildsize);
    return this;
  }

  // / [o] return timestamp kind(Hardware, Driver, DCAM etc..)
  @CLong
  @Field(4)
  public long timestampkind()
  {
    return this.io.getCLongField(this, 4);
  }

  // / [o] return timestamp kind(Hardware, Driver, DCAM etc..)
  @CLong
  @Field(4)
  public DCAM_TIMESTAMPBLOCK timestampkind(final long timestampkind)
  {
    this.io.setCLongField(this, 4, timestampkind);
    return this;
  }

  @CLong
  @Field(5)
  public long reserved()
  {
    return this.io.getCLongField(this, 5);
  }

  @CLong
  @Field(5)
  public DCAM_TIMESTAMPBLOCK reserved(final long reserved)
  {
    this.io.setCLongField(this, 5, reserved);
    return this;
  }

  public DCAM_TIMESTAMPBLOCK(final Pointer pointer)
  {
    super(pointer);
  }
}
