package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:370</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAMBUF_ATTACH extends StructObject
{
  public DCAMBUF_ATTACH()
  {
    super();
  }

  // / [in]
  @CLong
  @Field(0)
  public long size()
  {
    return this.io.getCLongField(this, 0);
  }

  // / [in]
  @CLong
  @Field(0)
  public DCAMBUF_ATTACH size(final long size)
  {
    this.io.setCLongField(this, 0, size);
    return this;
  }

  // / [in] DCAMBUF_ATTACHKIND
  @CLong
  @Field(1)
  public long iKind()
  {
    return this.io.getCLongField(this, 1);
  }

  // / [in] DCAMBUF_ATTACHKIND
  @CLong
  @Field(1)
  public DCAMBUF_ATTACH iKind(final long iKind)
  {
    this.io.setCLongField(this, 1, iKind);
    return this;
  }

  /**
   * [in,ptr]<br>
   * C type : void**
   */
  @Field(2)
  public Pointer<Pointer<?>> buffer()
  {
    return this.io.getPointerField(this, 2);
  }

  /**
   * [in,ptr]<br>
   * C type : void**
   */
  @Field(2)
  public DCAMBUF_ATTACH buffer(final Pointer<Pointer<?>> buffer)
  {
    this.io.setPointerField(this, 2, buffer);
    return this;
  }

  // / [in]
  @CLong
  @Field(3)
  public long buffercount()
  {
    return this.io.getCLongField(this, 3);
  }

  // / [in]
  @CLong
  @Field(3)
  public DCAMBUF_ATTACH buffercount(final long buffercount)
  {
    this.io.setCLongField(this, 3, buffercount);
    return this;
  }

  public DCAMBUF_ATTACH(final Pointer pointer)
  {
    super(pointer);
  }
}
