package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib/dcam/inc/dcamapi3.h</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_PARAM_FRAME_READOUT_TIME_INQ extends StructObject
{
  public DCAM_PARAM_FRAME_READOUT_TIME_INQ()
  {
    super();
  }

  /**
   * id == DCAM_IDPARAM_FRAME_READOUT_TIME_INQ<br>
   * C type : DCAM_HDR_PARAM
   */
  @Field(0)
  public DCAM_HDR_PARAM hdr()
  {
    return this.io.getNativeObjectField(this, 0);
  }

  /**
   * id == DCAM_IDPARAM_FRAME_READOUT_TIME_INQ<br>
   * C type : DCAM_HDR_PARAM
   */
  @Field(0)
  public DCAM_PARAM_FRAME_READOUT_TIME_INQ hdr(final DCAM_HDR_PARAM hdr)
  {
    this.io.setNativeObjectField(this, 0, hdr);
    return this;
  }

  // / [out]
  @Field(1)
  public double framereadouttime()
  {
    return this.io.getDoubleField(this, 1);
  }

  // / [out]
  @Field(1)
  public DCAM_PARAM_FRAME_READOUT_TIME_INQ framereadouttime(final double framereadouttime)
  {
    this.io.setDoubleField(this, 1, framereadouttime);
    return this;
  }

  public DCAM_PARAM_FRAME_READOUT_TIME_INQ(final Pointer pointer)
  {
    super(pointer);
  }
}
