package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:414</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAMWAIT_START extends StructObject
{
  public DCAMWAIT_START()
  {
    super();
  }

  @CLong
  @Field(0)
  public long size()
  {
    return this.io.getCLongField(this, 0);
  }

  @CLong
  @Field(0)
  public DCAMWAIT_START size(final long size)
  {
    this.io.setCLongField(this, 0, size);
    return this;
  }

  // / [out];
  @CLong
  @Field(1)
  public long eventhappened()
  {
    return this.io.getCLongField(this, 1);
  }

  // / [out];
  @CLong
  @Field(1)
  public DCAMWAIT_START eventhappened(final long eventhappened)
  {
    this.io.setCLongField(this, 1, eventhappened);
    return this;
  }

  // / [in]
  @CLong
  @Field(2)
  public long eventmask()
  {
    return this.io.getCLongField(this, 2);
  }

  // / [in]
  @CLong
  @Field(2)
  public DCAMWAIT_START eventmask(final long eventmask)
  {
    this.io.setCLongField(this, 2, eventmask);
    return this;
  }

  // / [in];
  @CLong
  @Field(3)
  public long timeout()
  {
    return this.io.getCLongField(this, 3);
  }

  // / [in];
  @CLong
  @Field(3)
  public DCAMWAIT_START timeout(final long timeout)
  {
    this.io.setCLongField(this, 3, timeout);
    return this;
  }

  public DCAMWAIT_START(final Pointer pointer)
  {
    super(pointer);
  }
}
