package dcamapi;

import dcamapi.DcamapiLibrary.DCAM_PIXELTYPE;

import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib\dcam\inc\dcamapi.h:386</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_FRAME extends StructObject
{
  public DCAM_FRAME()
  {
    super();
  }

  @CLong
  @Field(0)
  public long size()
  {
    return this.io.getCLongField(this, 0);
  }

  @CLong
  @Field(0)
  public DCAM_FRAME size(final long size)
  {
    this.io.setCLongField(this, 0, size);
    return this;
  }

  // / [in] 0 reserved
  @CLong
  @Field(1)
  public long iKind()
  {
    return this.io.getCLongField(this, 1);
  }

  // / [in] 0 reserved
  @CLong
  @Field(1)
  public DCAM_FRAME iKind(final long iKind)
  {
    this.io.setCLongField(this, 1, iKind);
    return this;
  }

  // / [i or o] reserved
  @CLong
  @Field(2)
  public long option()
  {
    return this.io.getCLongField(this, 2);
  }

  // / [i or o] reserved
  @CLong
  @Field(2)
  public DCAM_FRAME option(final long option)
  {
    this.io.setCLongField(this, 2, option);
    return this;
  }

  // / [in] frame index
  @CLong
  @Field(3)
  public long iFrame()
  {
    return this.io.getCLongField(this, 3);
  }

  // / [in] frame index
  @CLong
  @Field(3)
  public DCAM_FRAME iFrame(final long iFrame)
  {
    this.io.setCLongField(this, 3, iFrame);
    return this;
  }

  /**
   * [i or o] pointer for top-left image<br>
   * C type : void*
   */
  @Field(4)
  public Pointer<?> buf()
  {
    return this.io.getPointerField(this, 4);
  }

  /**
   * [i or o] pointer for top-left image<br>
   * C type : void*
   */
  @Field(4)
  public DCAM_FRAME buf(final Pointer<?> buf)
  {
    this.io.setPointerField(this, 4, buf);
    return this;
  }

  // / [i or o] byte size for next line.
  @CLong
  @Field(5)
  public long rowbytes()
  {
    return this.io.getCLongField(this, 5);
  }

  // / [i or o] byte size for next line.
  @CLong
  @Field(5)
  public DCAM_FRAME rowbytes(final long rowbytes)
  {
    this.io.setCLongField(this, 5, rowbytes);
    return this;
  }

  /**
   * [i or o] DCAM_PIXELTYPE_XXX<br>
   * C type : DCAM_PIXELTYPE
   */
  @Field(6)
  public IntValuedEnum<DCAM_PIXELTYPE> type()
  {
    return this.io.getEnumField(this, 6);
  }

  /**
   * [i or o] DCAM_PIXELTYPE_XXX<br>
   * C type : DCAM_PIXELTYPE
   */
  @Field(6)
  public DCAM_FRAME type(final IntValuedEnum<DCAM_PIXELTYPE> type)
  {
    this.io.setEnumField(this, 6, type);
    return this;
  }

  // / [i or o] horizontal pixel count
  @CLong
  @Field(7)
  public long width()
  {
    return this.io.getCLongField(this, 7);
  }

  // / [i or o] horizontal pixel count
  @CLong
  @Field(7)
  public DCAM_FRAME width(final long width)
  {
    this.io.setCLongField(this, 7, width);
    return this;
  }

  // / [i or o] vertical line count
  @CLong
  @Field(8)
  public long height()
  {
    return this.io.getCLongField(this, 8);
  }

  // / [i or o] vertical line count
  @CLong
  @Field(8)
  public DCAM_FRAME height(final long height)
  {
    this.io.setCLongField(this, 8, height);
    return this;
  }

  // / [i or o] (option) horizontal start pixel
  @CLong
  @Field(9)
  public long left()
  {
    return this.io.getCLongField(this, 9);
  }

  // / [i or o] (option) horizontal start pixel
  @CLong
  @Field(9)
  public DCAM_FRAME left(final long left)
  {
    this.io.setCLongField(this, 9, left);
    return this;
  }

  // / [i or o] (option) vertical start line
  @CLong
  @Field(10)
  public long top()
  {
    return this.io.getCLongField(this, 10);
  }

  // / [i or o] (option) vertical start line
  @CLong
  @Field(10)
  public DCAM_FRAME top(final long top)
  {
    this.io.setCLongField(this, 10, top);
    return this;
  }

  /**
   * [i or o] timestamp<br>
   * C type : DCAM_TIMESTAMP
   */
  @Field(11)
  public DCAM_TIMESTAMP timestamp()
  {
    return this.io.getNativeObjectField(this, 11);
  }

  /**
   * [i or o] timestamp<br>
   * C type : DCAM_TIMESTAMP
   */
  @Field(11)
  public DCAM_FRAME timestamp(final DCAM_TIMESTAMP timestamp)
  {
    this.io.setNativeObjectField(this, 11, timestamp);
    return this;
  }

  // / [i or o] framestamp
  @CLong
  @Field(12)
  public long framestamp()
  {
    return this.io.getCLongField(this, 12);
  }

  // / [i or o] framestamp
  @CLong
  @Field(12)
  public DCAM_FRAME framestamp(final long framestamp)
  {
    this.io.setCLongField(this, 12, framestamp);
    return this;
  }

  // / [in] 0 reserved
  @CLong
  @Field(13)
  public long reserved()
  {
    return this.io.getCLongField(this, 13);
  }

  // / [in] 0 reserved
  @CLong
  @Field(13)
  public DCAM_FRAME reserved(final long reserved)
  {
    this.io.setCLongField(this, 13, reserved);
    return this;
  }

  public DCAM_FRAME(final Pointer pointer)
  {
    super(pointer);
  }
}
