package dcamapi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : lib/dcam/inc/dcamapi3.h</i><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or
 * <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dcamapi")
public class DCAM_PARAM_SUBARRAY_INQ extends StructObject
{
  public DCAM_PARAM_SUBARRAY_INQ()
  {
    super();
  }

  /**
   * id == DCAM_IDPARAM_SUBARRAY_INQ<br>
   * C type : DCAM_HDR_PARAM
   */
  @Field(0)
  public DCAM_HDR_PARAM hdr()
  {
    return this.io.getNativeObjectField(this, 0);
  }

  /**
   * id == DCAM_IDPARAM_SUBARRAY_INQ<br>
   * C type : DCAM_HDR_PARAM
   */
  @Field(0)
  public DCAM_PARAM_SUBARRAY_INQ hdr(final DCAM_HDR_PARAM hdr)
  {
    this.io.setNativeObjectField(this, 0, hdr);
    return this;
  }

  // / [in]
  @Field(1)
  public int binning()
  {
    return this.io.getIntField(this, 1);
  }

  // / [in]
  @Field(1)
  public DCAM_PARAM_SUBARRAY_INQ binning(final int binning)
  {
    this.io.setIntField(this, 1, binning);
    return this;
  }

  // / [out]
  @Field(2)
  public int hmax()
  {
    return this.io.getIntField(this, 2);
  }

  // / [out]
  @Field(2)
  public DCAM_PARAM_SUBARRAY_INQ hmax(final int hmax)
  {
    this.io.setIntField(this, 2, hmax);
    return this;
  }

  // / [out]
  @Field(3)
  public int vmax()
  {
    return this.io.getIntField(this, 3);
  }

  // / [out]
  @Field(3)
  public DCAM_PARAM_SUBARRAY_INQ vmax(final int vmax)
  {
    this.io.setIntField(this, 3, vmax);
    return this;
  }

  // / [out]
  @Field(4)
  public int hposunit()
  {
    return this.io.getIntField(this, 4);
  }

  // / [out]
  @Field(4)
  public DCAM_PARAM_SUBARRAY_INQ hposunit(final int hposunit)
  {
    this.io.setIntField(this, 4, hposunit);
    return this;
  }

  // / [out]
  @Field(5)
  public int vposunit()
  {
    return this.io.getIntField(this, 5);
  }

  // / [out]
  @Field(5)
  public DCAM_PARAM_SUBARRAY_INQ vposunit(final int vposunit)
  {
    this.io.setIntField(this, 5, vposunit);
    return this;
  }

  // / [out]
  @Field(6)
  public int hunit()
  {
    return this.io.getIntField(this, 6);
  }

  // / [out]
  @Field(6)
  public DCAM_PARAM_SUBARRAY_INQ hunit(final int hunit)
  {
    this.io.setIntField(this, 6, hunit);
    return this;
  }

  // / [out]
  @Field(7)
  public int vunit()
  {
    return this.io.getIntField(this, 7);
  }

  // / [out]
  @Field(7)
  public DCAM_PARAM_SUBARRAY_INQ vunit(final int vunit)
  {
    this.io.setIntField(this, 7, vunit);
    return this;
  }

  public DCAM_PARAM_SUBARRAY_INQ(final Pointer pointer)
  {
    super(pointer);
  }
}
